### ISSUE TITLE
FileNotFoundError: [Errno 2]

### ISSUE THREAD

**Issue by rosuaol** [yu4u/age-estimation-pytorch#14]
Thank you for the last answer for my question.

But I have another problem.
occur this error

Traceback (most recent call last):
  File "train.py", line 246, in <module>
    main()
  File "train.py", line 188, in main
    age_stddev=cfg.TRAIN.AGE_STDDEV)
  File "C:\Users\intel\Desktop\capstone\age-estimation-pytorch-master\dataset.py", line 52, in init
    df = pd.read_csv(str(csv_path))
  File "C:\Users\intel\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\intel\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, kwds)
  File "C:\Users\intel\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 880, in init
    self._make_engine(self.engine)
  File "C:\Users\intel\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, self.options)
  File "C:\Users\intel\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 1891, in init
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas_libs\parsers.pyx", line 374, in pandas._libs.parsers.TextReader.cinit
  File "pandas_libs\parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File \appa-real-release\gt_avg_train.csv does not exist: '\appa-real-release\gt_avg_train.csv'

How can I get this problem... please help me.   T.T

**Comment by yu4u** [comment]
Please check the argument `--data_dir [PATH/TO/appa-real-release]` is correct.

> FileNotFoundError: [Errno 2] File \appa-real-release\gt_avg_train.csv does not exist: '\appa-real-release\gt_avg_train.csv'
