### ISSUE TITLE
run train error

### ISSUE THREAD

**Issue by maikhang** [yu4u/age-estimation-pytorch#21]
Hello, I'm having a problem, when i run cmd "python train.py --data_dir data/appa-real-release --multi_gpu --tensorboard tf_log", struck a error: 
```
=> creating model 'se_resnext50_32x4d'
2021-03-13 02:19:44.210801: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-03-13 02:19:44.211070: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
  0%|                                                                                                                    | 0/31 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 246, in <module>
    main()
  File "train.py", line 206, in main
    train_loss, train_acc = train(train_loader, model, criterion, optimizer, epoch, device)
  File "train.py", line 62, in train
    for x, y in _tqdm:
  File "C:\Users\sungh\AppData\Local\Programs\Python\Python38\lib\site-packages\tqdm\_tqdm.py", line 1017, in __iter__
    for obj in iterable:
  File "C:\Users\sungh\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "C:\Users\sungh\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 1199, in _next_data   
    return self._process_data(data)
  File "C:\Users\sungh\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 1225, in _process_data
    data.reraise()
  File "C:\Users\sungh\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\sungh\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\_utils\worker.py", line 202, in _worker_loop    
    data = fetcher.fetch(index)
  File "C:\Users\sungh\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\sungh\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>        
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "G:\python_project\age-estimation-pytorch-master\dataset.py", line 80, in __getitem__
    img = self.transform(img).astype(np.float32)
  File "G:\python_project\age-estimation-pytorch-master\dataset.py", line 31, in __call__
    img = self.aug.augment_image(img)
  File "C:\Users\sungh\AppData\Local\Programs\Python\Python38\lib\site-packages\imgaug\augmenters\meta.py", line 771, in augment_image
    return self.augment_images([image], hooks=hooks)[0]
  File "C:\Users\sungh\AppData\Local\Programs\Python\Python38\lib\site-packages\imgaug\augmenters\meta.py", line 822, in augment_images
    return self.augment_batch_(
  File "C:\Users\sungh\AppData\Local\Programs\Python\Python38\lib\site-packages\imgaug\augmenters\meta.py", line 641, in augment_batch_
    batch_inaug = self._augment_batch_(
  File "C:\Users\sungh\AppData\Local\Programs\Python\Python38\lib\site-packages\imgaug\augmenters\meta.py", line 3124, in _augment_batch_        
    batch = self[index].augment_batch_(
  File "C:\Users\sungh\AppData\Local\Programs\Python\Python38\lib\site-packages\imgaug\augmenters\meta.py", line 641, in augment_batch_
    batch_inaug = self._augment_batch_(
  File "C:\Users\sungh\AppData\Local\Programs\Python\Python38\lib\site-packages\imgaug\augmenters\color.py", line 2470, in _augment_batch_       
    image_hsv = self._transform_image_cv2(
  File "C:\Users\sungh\AppData\Local\Programs\Python\Python38\lib\site-packages\imgaug\augmenters\color.py", line 2501, in _transform_image_cv2  
    table_hue = cls._LUT_CACHE[0]
TypeError: 'NoneType' object is not subscriptable
```

**Anyone helps me, thanks so much !!!**

**Comment by David-on-Code** [comment]
Have you solve it? I also encountered this problem.

**Comment by maikhang** [comment]
> Have you solve it? I also encountered this problem.

sorry i'm still not :(

**Comment by David-on-Code** [comment]
I have solve it. But I don't know whether it suits you. I just use one GPU,so I set the worker=0.

**Comment by maikhang** [comment]
> I have solve it. But I don't know whether it suits you. I just use one GPU,so I set the worker=0.

I think I have fixed it thanks to your suggestion, sorry for the late reply, thank you so much.

**Comment by VegetableChlcken** [comment]
> > I have solve it. But I don't know whether it suits you. I just use one GPU,so I set the worker=0.
> 
> I think I have fixed it thanks to your suggestion, sorry for the late reply, thank you so much.

Hello, this problem is that imgaug calls the cv2 function in dataloader during multi-GPU training. You can solve this problem by replacing self._transform_image_cv2 with self._transform_image_numpy in imgaug/augmenters/color.py in 2469 lines.
